import flet as ft

RAIL_WIDTH = 72
MENU_WIDTH = 248

SIDEBAR_BG = ft.Colors.SURFACE_CONTAINER_LOW
RAIL_BG = ft.Colors.SURFACE_CONTAINER
MENU_BG = ft.Colors.SURFACE
CONTENT_BG = ft.Colors.SURFACE_CONTAINER_LOWEST

RAIL_ICON_DEFAULT = ft.Colors.ON_SURFACE_VARIANT
RAIL_ICON_SELECTED = ft.Colors.ON_PRIMARY_CONTAINER
RAIL_BTN_SELECTED_BG = ft.Colors.PRIMARY_CONTAINER

MENU_HEADER_COLOR = ft.Colors.ON_SURFACE
MENU_SUBTITLE_COLOR = ft.Colors.ON_SURFACE_VARIANT
ITEM_SELECTED_BG = ft.Colors.SECONDARY_CONTAINER
ITEM_SELECTED_COLOR = ft.Colors.ON_SECONDARY_CONTAINER
